apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-frontend
  namespace: quantum
  labels:
    app: quantum-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantum-frontend
  template:
    metadata:
      labels:
        app: quantum-frontend
    spec:
      containers:
      - name: frontend
        image: project-quantum-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-frontend-service
  namespace: quantum
  labels:
    app: quantum-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: quantum-frontend
  type: NodePort
