FROM grafana/grafana:latest

# Copy data source and dashboard provisioning files
COPY provisioning /etc/grafana/provisioning

# Copy the actual JSON dashboard configuration
COPY grafana-dashboard.json /var/lib/grafana/dashboards/grafana-dashboard.json
